-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Dosen"
(
    "NIP" integer NOT NULL,
    "Nama " character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Dosen_pkey" PRIMARY KEY ("NIP")
);

CREATE TABLE IF NOT EXISTS public."Mahasiswa"
(
    "NRP" integer NOT NULL,
    "Nama" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Mahasiswa_pkey" PRIMARY KEY ("NRP")
);

CREATE TABLE IF NOT EXISTS public."Mata Kuliah "
(
    "ID" integer NOT NULL,
    "Nama" character varying COLLATE pg_catalog."default" NOT NULL,
    "Jam" date NOT NULL,
    "Ruang " character varying NOT NULL,
    CONSTRAINT "Mata Kuliah _pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Mahasiswa_Mata Kuliah "
(
    "Mahasiswa_NRP" integer NOT NULL,
    "Mata Kuliah _ID" integer NOT NULL
);

ALTER TABLE IF EXISTS public."Dosen"
    ADD FOREIGN KEY ("NIP")
    REFERENCES public."Mata Kuliah " ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mahasiswa_Mata Kuliah "
    ADD FOREIGN KEY ("Mahasiswa_NRP")
    REFERENCES public."Mahasiswa" ("NRP") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mahasiswa_Mata Kuliah "
    ADD FOREIGN KEY ("Mata Kuliah _ID")
    REFERENCES public."Mata Kuliah " ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;